### ISSUE TITLE
網址失效了

### ISSUE THREAD

**Issue by Iornia** [iultimatez/iultimatez.github.io#1]
您好，在dcard大學新生季看到您的貼文，覺得是很方便、厲害的工具，但是網址似乎失效了，想請問能不能將網站假設回來呢？謝謝！

**Comment by iultimatez** [comment]
您好，感謝您的留言。本來這只是為了去年分科測驗做的一次性的網站，不過我剛剛已經更新了資料並且把網站重新上線了。有問題請回報，感謝！
